### ISSUE TITLE
algunas cuestiones

### ISSUE THREAD

**Issue by Tbo29** [WhiteNeo/thankyou-mybb-system-mybb18x-series#1]
Hola Dark Neo,

hay algunas cuestiones:

1) Cuando hago la desinstalación da un error: 1050 - ya existe la tabla 'mybb_thx_backup_26012015'

2) No elimina los valores del archivo inc / settings.php, por lo tanto, al volver a instalar el plugin no añade la hoja de estilo y las plantilla más y mantiene todos los ajustes de settings.

Yo todavía estoy probando en mi localhost.

**Comment by WhiteNeo** [comment]
Es que únicamente debe hacer todo al crear la 1ra vez, luego de esto ya debe cargar sólo lo que necesite, osea nada, dejando tus ajustes y hoja de estilo en caso de cambios intacta, antes creaba todo de nuevo y esto era incómodo a todos.

Si desinstalas dos veces sucederá eso en el mismo día, ya que se crea la base de datos de la fecha que tienes tomando el formato de la fecha actual únicamente, en la guia que deje viene que debes renombrar manualmente a thx la tabla thx_backup asi deja intactos tus agradecimientos igualmente es para evitar que te elimine tus cosas guardadas :D no son errores son mas bien mlas manipulaciones de usuarios.

Nunca deberías desinstalar y reinstalar más de una ocasión un plugin ya que no es correcto xD. Sólo cargaría más sentencias a la base que no son necesarias xD, en fin es mas bien un sistema de protección mediante la cache. Aunque debiera eliminarte todo en la 1ra vez con la última acualización que subi hace un par de días. Por demás renombra esa tabla via phpmyadmin, asi sólo el admin sabrá cuando alguien ha desinstalado tu plugin en caso de que algo raro suceda como a mi a veces, asi ya sé que cosa xD. Es un control interno y las opciones y ajustes no son tocados si es que no tienes la última revisión, puedes hacer una prueba. Cambiando la versión en el thx_info a 2.5.2 por ejemplo que sería mas arriba aunque a veces solo coge los primeros dos número al hacer comparaciones si colocas 2.6 en version entonces actualizará todo, en caso contrario no hará nada ya que se supone que el sistema debe estar instalado ya. Sin embargo haciendo esto de 2.6 es que se podría reinstalar o desinstalando ya que agregue eliminar la cache por lo cual ya no cogería nada y tendría que cargar todo xD. 

Al instalar de nuevo o tener instalado elimina la tabla txh y la que dice thx_backup_lafecha renombrala a thx y listo !!! deberá funcionarte todo.

Saludos...

**Comment by Tbo29** [comment]
Sí, todo está claro. Me di cuenta de cómo funciona y he eliminado la tabla manualmente. Hice varias instalaciones y desinstalaciones porque he cambiado las plantillas y quería ver si lo he hecho todo correctamente y todo funciona antes de instalarlo en mi foro en línea.

Yo he adaptado el plugin para mis necesidades y ahora tengo un sistema de "Me gusta" como en FB.

**Comment by WhiteNeo** [comment]
Si muchos me han dicho de el sistema de ese modo, ya estoy haciendo una versión más sencilla con ese sistema de Likes, sin embargo no lo terminaré aún ya que tengote muchas dudas sobre el funcionamiento final del mismo.

Cierro este hilo ya que no es un error, sino mas bien algo normal del plugin :dart:
